// ---------------------------------------------------------------------------
// TRANSCRIBE THE VO — hear what's actually ON TAPE, not what we scripted.
//
// The announcer (and every LSW) is generated by gemini-3.1-flash-tts, but a
// take can come out WRONG — the model drops a word, mangles a name, reads a
// tag aloud, or the sci-fi FX pass buries it. This tool runs the recorded
// WAVs back through whisper, diffs the transcript against the written line,
// and prints THE DIRECTOR'S NOTES: every take that drifted from its script,
// so the bad ones can be redone (gen-lsw-vo.mjs --only <slot> --force).
//
//   node tools/transcribe-vo.mjs                 # all announcer (ann_*) lines
//   node tools/transcribe-vo.mjs --all           # + every LSW voice line
//   node tools/transcribe-vo.mjs --lsw inferno   # one unit's ann + vo
//   node tools/transcribe-vo.mjs --only ann_titan_inbound
//   node tools/transcribe-vo.mjs --threshold 0.6 # how close counts as clean
//
// Writes tools/vo-transcript.json (machine) + docs/VO-DIRECTORS-NOTES.md
// (the redo list). Zero deps beyond findToken + whisper on Replicate.
// ---------------------------------------------------------------------------
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { findToken } from './tts-core.mjs';
import { VO, ANN } from './lsw-vo-script.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const AUDIO = join(ROOT, 'public', 'audio');
const WHISPER = 'vaibhavs10/incredibly-fast-whisper';

// ---- args ----------------------------------------------------------------
const argv = process.argv.slice(2);
const flag = (name) => { const i = argv.indexOf(name); return i >= 0 ? argv[i + 1] : null; };
const onlySlot = flag('--only');
const lsw = flag('--lsw');
const withVo = argv.includes('--all') || !!lsw;
const threshold = Number(flag('--threshold') ?? 0.62);
const limit = Number(flag('--limit') ?? 0); // 0 = no cap
const CONCURRENCY = 4;

// ---- the script: slot -> written line ------------------------------------
const script = new Map();
for (const e of ANN) script.set(e.slot, e.text);
if (withVo) for (const e of VO) script.set(e.slot, e.text);

// which slots to check
let slots = [...script.keys()];
if (onlySlot) slots = slots.filter((s) => s === onlySlot);
else if (lsw) slots = slots.filter((s) => s === `ann_${lsw}_inbound` || s === `ann_${lsw}_landed` || s === `ann_${lsw}_down` || s === `ann_${lsw}_rampage` || s.startsWith(`vo_${lsw}_`));
else if (!withVo) slots = slots.filter((s) => s.startsWith('ann_'));
if (limit > 0) slots = slots.slice(0, limit);

// ---- normalize a line so scripted vs heard compare fairly ----------------
// drop [director tags], lowercase, strip punctuation, collapse whitespace,
// spell out the ordinals the script writes as digits ("5 KILLS" ~ "five")
function norm(s) {
  return (s || '')
    .replace(/\[[^\]]*\]/g, ' ')            // [short pause], [booming] ...
    .toLowerCase()
    .replace(/\bfive\b/g, '5')
    .replace(/[^a-z0-9 ]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// character-bigram Dice on the space-collapsed strings — this is what makes
// "shadow step" match "shadowstep": whisper splits compound LSW names and
// that alone tanked a word-bag score on a 3-word line (a false "OFF").
function charDice(a, b) {
  const grams = (s) => { const g = new Map(); const t = norm(s).replace(/ /g, ''); for (let i = 0; i < t.length - 1; i++) { const k = t.slice(i, i + 2); g.set(k, (g.get(k) || 0) + 1); } return g; };
  const ga = grams(a), gb = grams(b);
  let na = 0, nb = 0, inter = 0;
  for (const v of ga.values()) na += v;
  for (const [k, v] of gb) { nb += v; if (ga.has(k)) inter += Math.min(v, ga.get(k)); }
  if (!na && !nb) return 1;
  return (2 * inter) / (na + nb);
}

// similarity = the kinder of word-overlap and char-bigram, so a genuine
// drift (a whole prompt spoken) still scores low, but a split name doesn't.
function similarity(a, b) {
  const wa = new Set(norm(a).split(' ').filter(Boolean));
  const wb = new Set(norm(b).split(' ').filter(Boolean));
  let jac = 1;
  if (wa.size || wb.size) {
    let inter = 0;
    for (const w of wa) if (wb.has(w)) inter++;
    jac = inter / (wa.size + wb.size - inter);
  }
  return Math.max(jac, charDice(a, b));
}

// ---- resolve the community model's latest version once --------------------
let _version = null;
async function whisperVersion(token) {
  if (_version) return _version;
  const r = await fetch(`https://api.replicate.com/v1/models/${WHISPER}`, { headers: { Authorization: `Bearer ${token}` } });
  if (!r.ok) throw new Error(`model lookup ${r.status}: ${(await r.text()).slice(0, 200)}`);
  const m = await r.json();
  _version = m.latest_version?.id;
  if (!_version) throw new Error('no latest_version for ' + WHISPER);
  return _version;
}

// ---- whisper one local WAV via a data URI --------------------------------
async function transcribe(token, wavPath) {
  const version = await whisperVersion(token);
  const b64 = readFileSync(wavPath).toString('base64');
  const dataUri = `data:audio/wav;base64,${b64}`;
  const res = await fetch('https://api.replicate.com/v1/predictions', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', Prefer: 'wait' },
    body: JSON.stringify({ version, input: { audio: dataUri, task: 'transcribe', language: 'english', batch_size: 64 } }),
  });
  if (!res.ok) throw new Error(`whisper ${res.status}: ${(await res.text()).slice(0, 200)}`);
  let pred = await res.json();
  let tries = 0;
  while ((pred.status === 'starting' || pred.status === 'processing') && tries++ < 120) {
    await new Promise((r) => setTimeout(r, 1200));
    pred = await (await fetch(pred.urls.get, { headers: { Authorization: `Bearer ${token}` } })).json();
  }
  if (pred.status !== 'succeeded') throw new Error(`whisper ${pred.status}: ${pred.error ?? 'no detail'}`);
  const o = pred.output;
  return (typeof o === 'string' ? o : (o?.text ?? '')).trim();
}

// ---- run, gently, in small batches ---------------------------------------
async function main() {
  const token = findToken();
  if (!token) { console.error('No REPLICATE_API_TOKEN/REPLICATE_API_KEY (env or house .env chain).'); process.exit(1); }

  const rows = [];
  const queue = [...slots];
  console.log(`Transcribing ${queue.length} take(s) through ${WHISPER}…\n`);

  async function worker() {
    for (;;) {
      const slot = queue.shift();
      if (!slot) return;
      const wav = join(AUDIO, `${slot}.wav`);
      if (!existsSync(wav)) { rows.push({ slot, scripted: script.get(slot), heard: null, sim: 0, status: 'MISSING' }); continue; }
      try {
        const heard = await transcribe(token, wav);
        const scripted = script.get(slot);
        const sim = similarity(scripted, heard);
        rows.push({ slot, scripted, heard, sim: +sim.toFixed(2), status: sim >= threshold ? 'ok' : 'OFF' });
        process.stdout.write(sim >= threshold ? '.' : 'x');
      } catch (e) {
        rows.push({ slot, scripted: script.get(slot), heard: null, sim: 0, status: 'ERR', err: String(e.message || e) });
        process.stdout.write('!');
      }
    }
  }
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));
  rows.sort((a, b) => a.slot.localeCompare(b.slot));

  const off = rows.filter((r) => r.status === 'OFF');
  const missing = rows.filter((r) => r.status === 'MISSING');
  const errored = rows.filter((r) => r.status === 'ERR');
  const clean = rows.filter((r) => r.status === 'ok');

  // machine-readable
  writeFileSync(join(ROOT, 'tools', 'vo-transcript.json'), JSON.stringify({ generated: 'run', threshold, rows }, null, 2));

  // the director's notes — the redo list, human-first
  const lines = [];
  lines.push('# VO — Director\'s Notes (what\'s actually on tape)', '');
  lines.push(`Transcribed ${rows.length} take(s) back through whisper and diffed against the script.`);
  lines.push(`Clean: ${clean.length} · **Off-script: ${off.length}** · Missing: ${missing.length} · Errored: ${errored.length} · match threshold ${threshold}.`, '');
  if (off.length) {
    lines.push('## Redo these — the take drifted from the line', '');
    lines.push('| slot | match | scripted | heard on tape |');
    lines.push('|---|---|---|---|');
    for (const r of off) lines.push(`| \`${r.slot}\` | ${r.sim} | ${(r.scripted || '').replace(/\|/g, '\\|')} | ${(r.heard || '').replace(/\|/g, '\\|')} |`);
    lines.push('', '**To redo:** `node tools/gen-lsw-vo.mjs --only <slot> --force`  (edit the line/direction in `tools/lsw-vo-script.mjs` first if the SCRIPT is what\'s wrong).', '');
  } else {
    lines.push('## Every take matches its script. Nothing to redo. ✅', '');
  }
  if (missing.length) lines.push('## Missing on disk', '', ...missing.map((r) => `- \`${r.slot}\``), '');
  if (errored.length) lines.push('## Transcription errored (retry)', '', ...errored.map((r) => `- \`${r.slot}\` — ${r.err}`), '');
  lines.push('## Full transcript', '', '| slot | match | heard on tape |', '|---|---|---|');
  for (const r of rows) lines.push(`| \`${r.slot}\` | ${r.status === 'ok' ? r.sim : r.status} | ${(r.heard || '—').replace(/\|/g, '\\|')} |`);
  mkdirSync(join(ROOT, 'docs'), { recursive: true });
  writeFileSync(join(ROOT, 'docs', 'VO-DIRECTORS-NOTES.md'), lines.join('\n') + '\n');

  console.log(`\n\nDONE — ${clean.length} clean, ${off.length} OFF-script, ${missing.length} missing, ${errored.length} errored.`);
  if (off.length) {
    console.log('\nOFF-SCRIPT (redo candidates):');
    for (const r of off) console.log(`  ${r.slot}  [${r.sim}]  scripted="${r.scripted}"  heard="${r.heard}"`);
  }
  console.log('\nWrote docs/VO-DIRECTORS-NOTES.md + tools/vo-transcript.json');
}

main().catch((e) => { console.error(e); process.exit(1); });
